site_name: TechModa AWS Labs
site_description: Laboratories for AWS High Availability and Disaster Recovery
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - tables
  - def_list

nav:
  - Home: index.md
  - Labs:
    - Overview: labs/index.md
    - High Availability & Disaster Recovery:
      - Introduction: labs/ha-dr/index.md
      - Lab 1: Setting up Multi-AZ Architecture: labs/ha-dr/lab1.md
      - Lab 2: Implementing Auto Scaling: labs/ha-dr/lab2.md
      - Lab 3: Disaster Recovery Strategies: labs/ha-dr/lab3.md
      - Lab 4: Monitoring with CloudWatch: labs/ha-dr/lab4.md
      - Lab 5: Implementing Backup Solutions: labs/ha-dr/lab5.md
  - Resources: resources.md